# -*- coding: utf-8 -*-
"""Naissance_deces.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DsL045aQrT_LD8_U6HNqFAwadXtVcORQ
"""

import pandas as pd
import requests
import time


SPARQL_ENDPOINT = "https://data.idref.fr/sparql"


# ============================================================
# NORMALISATION PPN
# ============================================================

def normaliser_ppn(ppn):

    if pd.isna(ppn):
        return None

    ppn = str(ppn).strip()

    if ppn == "" or ppn.lower() in {
        "nan",
        "none",
        "null",
        "<na>"
    }:
        return None

    # Cas éventuel : 123456789.0
    if ppn.endswith(".0"):
        ppn = ppn[:-2]

    return ppn


# ============================================================
# EXTRACTION DE L'ANNEE
# ============================================================

def extraire_annee(date):

    if date is None:
        return None

    date = str(date).strip()

    if not date:
        return None

    # Exemples :
    # 1878-09-24 -> 1878
    # 1952       -> 1952

    return date[:4]


# ============================================================
# REQUETE SPARQL POUR UN LOT DE PPN
# ============================================================

def recuperer_dates_lot(
    ppns,
    session,
    timeout=30,
    max_retries=3
):

    if not ppns:

        return pd.DataFrame(
            columns=[
                "ppn",
                "date_naissance",
                "date_deces"
            ]
        )


    # --------------------------------------------------------
    # Construction VALUES
    # --------------------------------------------------------

    values = "\n".join(
        f'"{ppn}"'
        for ppn in ppns
    )


    # --------------------------------------------------------
    # Requête SPARQL
    # --------------------------------------------------------

    query = f"""
    PREFIX bio: <http://purl.org/vocab/bio/0.1/>

    SELECT
        ?ppn
        ?date_naissance
        ?date_deces

    WHERE {{

        VALUES ?ppn {{
            {values}
        }}

        BIND(
            IRI(
                CONCAT(
                    "http://www.idref.fr/",
                    ?ppn,
                    "/birth"
                )
            )
            AS ?birth
        )

        BIND(
            IRI(
                CONCAT(
                    "http://www.idref.fr/",
                    ?ppn,
                    "/death"
                )
            )
            AS ?death
        )

        OPTIONAL {{
            ?birth
                bio:date
                ?date_naissance .
        }}

        OPTIONAL {{
            ?death
                bio:date
                ?date_deces .
        }}

    }}
    ORDER BY ?ppn
    """


    # --------------------------------------------------------
    # Appel avec retries
    # --------------------------------------------------------

    for tentative in range(
        1,
        max_retries + 1
    ):

        try:

            response = session.get(
                SPARQL_ENDPOINT,
                params={
                    "query": query,
                    "format":
                        "application/sparql-results+json"
                },
                headers={
                    "Accept":
                        "application/sparql-results+json",
                    "User-Agent":
                        "Python-BGE/1.0"
                },
                timeout=timeout
            )

            response.raise_for_status()

            data = response.json()

            break

        except requests.RequestException as e:

            print(
                f"Erreur tentative "
                f"{tentative}/{max_retries} : {e}"
            )

            if tentative == max_retries:

                return pd.DataFrame(
                    columns=[
                        "ppn",
                        "date_naissance",
                        "date_deces"
                    ]
                )

            time.sleep(
                2 ** (tentative - 1)
            )


    # --------------------------------------------------------
    # Lecture résultats
    # --------------------------------------------------------

    bindings = (
        data
        .get("results", {})
        .get("bindings", [])
    )


    resultats = []


    for ligne in bindings:

        ppn = (
            ligne
            .get("ppn", {})
            .get("value")
        )

        naissance = (
            ligne
            .get("date_naissance", {})
            .get("value")
        )

        deces = (
            ligne
            .get("date_deces", {})
            .get("value")
        )


        # ----------------------------------------------------
        # On garde uniquement l'année
        # ----------------------------------------------------

        naissance = extraire_annee(
            naissance
        )

        deces = extraire_annee(
            deces
        )


        resultats.append({

            "ppn": ppn,

            "date_naissance":
                naissance,

            "date_deces":
                deces

        })


    return pd.DataFrame(
        resultats
    )


# ============================================================
# FONCTION PRINCIPALE
# ============================================================

def ajouter_dates_auteurs(
    df,
    taille_lot=100,
    timeout=30,
    afficher_progression=True
):

    """
    Ajoute les années de naissance et de décès
    des auteurs grâce au PPN IdRef.

    Le DataFrame doit contenir une colonne :
        ppn

    Retourne le DataFrame avec :
        date_naissance
        date_deces

    Seule l'année est conservée.

    Exemple :
        1878-09-24 -> 1878
        1947-05-23 -> 1947
        1952       -> 1952
    """


    # ========================================================
    # Vérification
    # ========================================================

    if "ppn" not in df.columns:

        raise ValueError(
            "La colonne 'ppn' "
            "n'existe pas dans le DataFrame."
        )


    # ========================================================
    # Copie
    # ========================================================

    df_resultat = df.copy()


    # ========================================================
    # Normalisation temporaire des PPN
    # ========================================================

    df_resultat["_ppn_temp"] = (
        df_resultat["ppn"]
        .map(normaliser_ppn)
    )


    # ========================================================
    # Liste unique
    # ========================================================

    ppns_uniques = (
        df_resultat["_ppn_temp"]
        .dropna()
        .drop_duplicates()
        .tolist()
    )


    print(
        "Nombre de PPN uniques à interroger :",
        len(ppns_uniques)
    )


    # ========================================================
    # Aucun PPN
    # ========================================================

    if not ppns_uniques:

        df_resultat[
            "date_naissance"
        ] = pd.NA

        df_resultat[
            "date_deces"
        ] = pd.NA

        df_resultat.drop(
            columns="_ppn_temp",
            inplace=True
        )

        return df_resultat


    # ========================================================
    # Session HTTP réutilisée
    # ========================================================

    session = requests.Session()


    # ========================================================
    # Découpage en lots
    # ========================================================

    resultats = []


    nombre_lots = (
        len(ppns_uniques)
        + taille_lot
        - 1
    ) // taille_lot


    for numero_lot, debut in enumerate(
        range(
            0,
            len(ppns_uniques),
            taille_lot
        ),
        start=1
    ):


        lot = ppns_uniques[
            debut:
            debut + taille_lot
        ]


        if afficher_progression:

            print(
                f"Lot "
                f"{numero_lot}/"
                f"{nombre_lots}"
                f" - "
                f"{len(lot)} PPN"
            )


        df_lot = recuperer_dates_lot(
            lot,
            session=session,
            timeout=timeout
        )


        if not df_lot.empty:

            resultats.append(
                df_lot
            )


    session.close()


    # ========================================================
    # Aucun résultat
    # ========================================================

    if not resultats:

        df_resultat[
            "date_naissance"
        ] = pd.NA

        df_resultat[
            "date_deces"
        ] = pd.NA

        df_resultat.drop(
            columns="_ppn_temp",
            inplace=True
        )

        return df_resultat


    # ========================================================
    # Fusion de tous les lots
    # ========================================================

    df_dates = pd.concat(
        resultats,
        ignore_index=True
    )


    # ========================================================
    # Sécurité contre doublons
    # ========================================================

    df_dates = (
        df_dates
        .drop_duplicates(
            subset="ppn",
            keep="first"
        )
    )


    # ========================================================
    # Renommage clé de fusion
    # ========================================================

    df_dates = df_dates.rename(
        columns={
            "ppn":
                "_ppn_temp"
        }
    )


    # ========================================================
    # Fusion avec DataFrame d'origine
    # ========================================================

    df_resultat = (
        df_resultat
        .merge(
            df_dates,
            on="_ppn_temp",
            how="left"
        )
    )


    # ========================================================
    # Suppression clé temporaire
    # ========================================================

    df_resultat.drop(
        columns="_ppn_temp",
        inplace=True
    )


    return df_resultat