# -*- coding: utf-8 -*-
"""nettoyage.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w72LkpAQ1z0xHlZ-uGhBgJ9gAdGoFpXu
"""

# -*- coding: utf-8 -*-

import os
import pandas as pd


# ============================================================
# NETTOYAGE FINAL
# ============================================================

def nettoyage(
    df,
    dossier_output
):
    """
    Effectue tout le nettoyage final du projet BGE
    et enregistre automatiquement le résultat sous :

        resultat_final.csv

    dans le dossier output.

    Paramètres
    ----------
    df : pandas.DataFrame
        DataFrame issu de la comparaison VGE et du
        dédoublonnage final.

    dossier_output : str
        Dossier dans lequel enregistrer resultat_final.csv.

    Retour
    ------
    pandas.DataFrame
        DataFrame final nettoyé.
    """

    # ========================================================
    # VERIFICATIONS
    # ========================================================

    if df is None:

        raise ValueError(
            "Le DataFrame fourni à nettoyage() est None."
        )


    if not isinstance(
        df,
        pd.DataFrame
    ):

        raise TypeError(
            f"Objet reçu invalide : {type(df)}"
        )


    # ========================================================
    # COPIE
    # ========================================================

    df = df.copy()


    print()
    print("=" * 70)
    print("NETTOYAGE FINAL")
    print("=" * 70)

    print(
        f"Lignes reçues : "
        f"{len(df):,}"
    )


    # ========================================================
    # FONCTION INTERNE :
    # FUSIONNER DES VALEURS SEPAREES PAR |
    # ========================================================

    def fusionner_valeurs(
        *valeurs
    ):

        elements = []


        for valeur in valeurs:

            # ------------------------------------------------
            # Valeur vide
            # ------------------------------------------------

            if pd.isna(
                valeur
            ):
                continue


            valeur = str(
                valeur
            ).strip()


            if not valeur:
                continue


            # ------------------------------------------------
            # Découpage
            # ------------------------------------------------

            morceaux = [

                morceau.strip()

                for morceau
                in valeur.split("|")

                if morceau.strip()
            ]


            elements.extend(
                morceaux
            )


        # ----------------------------------------------------
        # Suppression doublons
        # conservation ordre initial
        # ----------------------------------------------------

        elements_uniques = list(
            dict.fromkeys(
                elements
            )
        )


        return " | ".join(
            elements_uniques
        )


    # ========================================================
    # 1. FUSION raisons + Raisons.1
    # ========================================================

    if "Raisons.1" in df.columns:


        if "raisons" not in df.columns:

            df["raisons"] = ""


        df["raisons"] = df.apply(

            lambda ligne:
                fusionner_valeurs(

                    ligne["raisons"],

                    ligne["Raisons.1"]
                ),

            axis=1
        )


        df = df.drop(
            columns=[
                "Raisons.1"
            ]
        )


    # ========================================================
    # 2. SUPPRESSION DES COLONNES INUTILES
    # ========================================================

    colonnes_a_supprimer = [

        "bnf_id",

        "gnd_id",

        "isbn",

        "ppn_sudoc",

        "ark_bnf",

        "relation_bnf",

        "idn_dnb",

        "Raisons"
    ]


    df = df.drop(

        columns=colonnes_a_supprimer,

        errors="ignore"
    )


    # ========================================================
    # 3. ISBN NORMALISE -> TEXTE
    # ========================================================

    if "isbn_normalise" in df.columns:

        df["isbn_normalise"] = (

            df["isbn_normalise"]

            .astype("string")

            .str.strip()

            .str.replace(
                r"\.0$",
                "",
                regex=True
            )
        )


    # ========================================================
    # 4. PPN -> TEXTE
    # ========================================================

    if "ppn" in df.columns:

        df["ppn"] = (

            df["ppn"]

            .astype("string")

            .str.strip()

            .str.replace(
                r"\.0$",
                "",
                regex=True
            )
        )


    # ========================================================
    # 5. ANNEE -> ENTIER NULLABLE
    # ========================================================

    if "annee" in df.columns:

        df["annee"] = (

            pd.to_numeric(

                df["annee"],

                errors="coerce"
            )

            .astype("Int64")
        )


    # ========================================================
    # 6. COLONNE ENSEMBLE
    #
    # Genevensia + lieu_publication
    #       -> Dépôt légal
    #
    # Genevensia sans lieu_publication
    #       -> Genevensia
    #
    # Autres recherches
    #       -> Auteur
    # ========================================================

    if "TypeRecherche" in df.columns:


        # ----------------------------------------------------
        # Valeur par défaut
        # ----------------------------------------------------

        df["Ensemble"] = "Auteur"


        # ----------------------------------------------------
        # Genevensia
        # ----------------------------------------------------

        masque_genevensia = (

            df["TypeRecherche"]

            .fillna("")

            .astype("string")

            .str.strip()

            .eq(
                "Genevensia"
            )
        )


        df.loc[

            masque_genevensia,

            "Ensemble"

        ] = "Genevensia"


        # ----------------------------------------------------
        # Dépôt légal
        # ----------------------------------------------------

        if "raisons" in df.columns:

            masque_depot_legal = (

                masque_genevensia

                &

                df["raisons"]

                .fillna("")

                .astype("string")

                .str.contains(

                    "lieu_publication",

                    case=False,

                    regex=False
                )
            )


            df.loc[

                masque_depot_legal,

                "Ensemble"

            ] = "Dépôt légal"


        # ----------------------------------------------------
        # TypeRecherche devenu inutile
        # ----------------------------------------------------

        df = df.drop(
            columns=[
                "TypeRecherche"
            ]
        )


    else:

        # ----------------------------------------------------
        # Sécurité si colonne absente
        # ----------------------------------------------------

        if "Ensemble" not in df.columns:

            df["Ensemble"] = "Auteur"


    # ========================================================
    # 7. nomAuteur
    #
    # Si nomAuteur est vide et que NomComplet existe,
    # prendre NomComplet.
    # ========================================================

    if "NomComplet" in df.columns:


        # ----------------------------------------------------
        # Créer nomAuteur si elle n'existe pas
        # ----------------------------------------------------

        if "nomAuteur" not in df.columns:

            df["nomAuteur"] = pd.NA


        masque_nom_vide = (

            df["nomAuteur"].isna()

            |

            df["nomAuteur"]

            .astype("string")

            .str.strip()

            .eq("")
        )


        df.loc[

            masque_nom_vide,

            "nomAuteur"

        ] = df.loc[

            masque_nom_vide,

            "NomComplet"
        ]


        # ----------------------------------------------------
        # NomComplet devenu inutile
        # ----------------------------------------------------

        df = df.drop(
            columns=[
                "NomComplet"
            ]
        )


    # ========================================================
    # 8. ACQUISITION
    # ========================================================

    if "Acquisition" not in df.columns:

        df["Acquisition"] = ""


    # ========================================================
    # 9. ORDRE DES COLONNES
    # ========================================================

    colonnes_prioritaires = [

        "ppn",

        "isbn_normalise",

        "titre",

        "annee",

        "nomAuteur",

        "lieuPublication",

        "editeur",

        "sujet",

        "raisons",

        "Source",

        "Ensemble",

        "Acquisition"
    ]


    colonnes_prioritaires = [

        colonne

        for colonne
        in colonnes_prioritaires

        if colonne in df.columns
    ]


    autres_colonnes = [

        colonne

        for colonne
        in df.columns

        if colonne
        not in colonnes_prioritaires
    ]


    df = df[

        colonnes_prioritaires

        +

        autres_colonnes
    ]


    # ========================================================
    # 10. RESET INDEX
    # ========================================================

    df = (
        df
        .reset_index(
            drop=True
        )
    )


    # ========================================================
    # 11. CREATION DOSSIER OUTPUT
    # ========================================================

    os.makedirs(

        dossier_output,

        exist_ok=True
    )


    # ========================================================
    # 12. ENREGISTREMENT CSV FINAL
    # ========================================================

    chemin_final = os.path.join(

        dossier_output,

        "resultat_final.csv"
    )


    df.to_csv(

        chemin_final,

        index=False
    )


    # ========================================================
    # 13. RESUME
    # ========================================================

    print()
    print(
        f"Lignes finales : "
        f"{len(df):,}"
    )


    if "isbn_normalise" in df.columns:

        print(
            f"ISBN uniques   : "
            f"{df['isbn_normalise'].nunique():,}"
        )


    if "Ensemble" in df.columns:

        print()

        print(
            "Répartition Ensemble :"
        )

        print(

            df["Ensemble"]

            .value_counts(
                dropna=False
            )

            .to_string()
        )


    print()

    print(
        f"Fichier enregistré : "
        f"{chemin_final}"
    )

    print("=" * 70)


    # ========================================================
    # RETURN
    # ========================================================

    return df