# -*- coding: utf-8 -*-
"""PPN gen_aut.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y70wsQDMohvAkZRYz0N0QjkzMIiBSqfa
"""

import pandas as pd
import requests
import time
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry


# ============================================================
# CONFIGURATION
# ============================================================

WIKIDATA_URL = "https://query.wikidata.org/sparql"

BATCH_SIZE = 150


# ============================================================
# SESSION HTTP OPTIMISÉE
# ============================================================

def creer_session():

    session = requests.Session()

    retry = Retry(
        total=5,
        connect=5,
        read=5,
        status=5,
        backoff_factor=1,
        status_forcelist=[429, 500, 502, 503, 504],
        allowed_methods=["GET", "POST"]
    )

    adapter = HTTPAdapter(
        max_retries=retry,
        pool_connections=10,
        pool_maxsize=10
    )

    session.mount("https://", adapter)

    session.headers.update({
        "User-Agent": "Geneve-Bibliographic-Research/1.0",
        "Accept": "application/sparql-results+json"
    })

    return session


# ============================================================
# REQUÊTE WIKIDATA PAR LOT DE PPN
# ============================================================

def requete_wikidata_ppn(ppns, session):

    valeurs = " ".join(
        f'"{str(ppn).strip()}"'
        for ppn in ppns
    )

    query = f"""
    SELECT
        ?ppn
        (SAMPLE(?nom) AS ?NomComplet)
        (GROUP_CONCAT(DISTINCT ?occupationLabel; separator=" | ") AS ?Occupations)
        (SAMPLE(?bnf) AS ?bnf_id)
        (SAMPLE(?gnd) AS ?gnd_id)

    WHERE {{

        VALUES ?ppn {{
            {valeurs}
        }}

        ?personne wdt:P269 ?ppn .

        OPTIONAL {{
            ?personne rdfs:label ?nom .
            FILTER(LANG(?nom) = "fr")
        }}

        OPTIONAL {{
            ?personne wdt:P106 ?occupation .

            ?occupation rdfs:label ?occupationLabel .

            FILTER(LANG(?occupationLabel) = "fr")
        }}

        OPTIONAL {{
            ?personne wdt:P268 ?bnf .
        }}

        OPTIONAL {{
            ?personne wdt:P227 ?gnd .
        }}
    }}

    GROUP BY ?ppn
    """

    response = session.get(
        WIKIDATA_URL,
        params={
            "query": query,
            "format": "json"
        },
        timeout=60
    )

    response.raise_for_status()

    data = response.json()

    lignes = []

    for x in data["results"]["bindings"]:

        lignes.append({

            "ppn": x["ppn"]["value"],

            "NomComplet_wikidata":
                x.get("NomComplet", {}).get("value"),

            "Occupations_wikidata":
                x.get("Occupations", {}).get("value"),

            "bnf_id_wikidata":
                x.get("bnf_id", {}).get("value"),

            "gnd_id_wikidata":
                x.get("gnd_id", {}).get("value")
        })

    return lignes


# ============================================================
# RÉCUPÉRER WIKIDATA POUR TOUS LES PPN
# ============================================================

def recuperer_wikidata(df, batch_size=BATCH_SIZE):

    session = creer_session()

    # --------------------------------------------------------
    # Sécurisation des PPN
    # --------------------------------------------------------

    ppns = (
        df["ppn"]
        .dropna()
        .astype(str)
        .str.strip()
        .drop_duplicates()
        .tolist()
    )

    resultats = []

    total = len(ppns)

    print(f"{total:,} PPN à rechercher sur Wikidata\n")

    # --------------------------------------------------------
    # Traitement par lots
    # --------------------------------------------------------

    for debut in range(0, total, batch_size):

        lot = ppns[debut:debut + batch_size]

        try:

            lignes = requete_wikidata_ppn(
                lot,
                session
            )

            resultats.extend(lignes)

            print(
                f"✓ {min(debut + batch_size, total):,}/{total:,}"
                f" — {len(lignes)} correspondances"
            )

        except Exception as e:

            print(
                f"✗ Lot {debut:,}-{debut + len(lot):,} : {e}"
            )

        # Petit délai pour respecter WDQS
        time.sleep(0.2)

    return pd.DataFrame(resultats)


# ============================================================
# FONCTION PRINCIPALE :
# COMPLÉTER LE DATAFRAME
# ============================================================

def completer_avec_wikidata(df):

    df = df.copy()

    # --------------------------------------------------------
    # PPN TOUJOURS EN TEXTE
    # --------------------------------------------------------

    df["ppn"] = (
        df["ppn"]
        .astype(str)
        .str.strip()
    )

    # --------------------------------------------------------
    # Colonnes attendues
    # --------------------------------------------------------

    colonnes = [
        "NomComplet",
        "Occupations",
        "Raisons",
        "bnf_id",
        "gnd_id"
    ]

    for col in colonnes:

        if col not in df.columns:
            df[col] = None

    # --------------------------------------------------------
    # Récupération Wikidata
    # --------------------------------------------------------

    df_wikidata = recuperer_wikidata(df)

    if df_wikidata.empty:

        print("\nAucune correspondance Wikidata trouvée.")

        return df

    # --------------------------------------------------------
    # Fusion
    # --------------------------------------------------------

    df = df.merge(
        df_wikidata,
        on="ppn",
        how="left"
    )

    # --------------------------------------------------------
    # Fonction permettant de reconnaître None / NaN / ""
    # --------------------------------------------------------

    def est_vide(serie):

        return (
            serie.isna()
            | serie.astype(str).str.strip().isin(
                ["", "None", "nan", "<NA>"]
            )
        )

    # --------------------------------------------------------
    # Compléter uniquement les champs manquants
    # --------------------------------------------------------

    correspondances = {

        "NomComplet":
            "NomComplet_wikidata",

        "Occupations":
            "Occupations_wikidata",

        "bnf_id":
            "bnf_id_wikidata",

        "gnd_id":
            "gnd_id_wikidata"
    }

    for colonne, colonne_wikidata in correspondances.items():

        masque = est_vide(df[colonne])

        df.loc[masque, colonne] = (
            df.loc[masque, colonne_wikidata]
        )

    # --------------------------------------------------------
    # Suppression colonnes temporaires
    # --------------------------------------------------------

    colonnes_wikidata = [
        c
        for c in df.columns
        if c.endswith("_wikidata")
    ]

    df = df.drop(
        columns=colonnes_wikidata
    )

    # --------------------------------------------------------
    # Remettre ordre original des colonnes
    # --------------------------------------------------------

    return df

def recuperer_ppn_gen_aut(rows=10000):

    url = "https://www.idref.fr/Sru/Solr"

    params = {
        "q": "classification_t:GEN_AUT",
        "sort": "score desc",
        "version": "2.2",
        "start": 0,
        "rows": rows,
        "fl": "ppn_z,persname_t",
        "wt": "json"
    }

    response = requests.get(
        url,
        params=params,
        timeout=60
    )

    response.raise_for_status()

    data = response.json()

    lignes = []

    for doc in data["response"]["docs"]:

        ppn = doc.get("ppn_z")
        nom_prenom = doc.get("persname_t")

        if isinstance(ppn, list):
            ppn = ppn[0] if ppn else None

        if isinstance(nom_prenom, list):
            nom_prenom = (
                nom_prenom[0]
                if nom_prenom
                else None
            )

        lignes.append({
            "ppn": ppn,
            "NomComplet": nom_prenom
        })

    df = pd.DataFrame(lignes)

    df = (
        df
        .dropna(subset=["ppn"])
        .drop_duplicates(subset=["ppn"])
        .reset_index(drop=True)
    )

    df["ppn"] = df["ppn"].astype(str)

    return df

# ============================================================
# FONCTION PRINCIPALE
# ============================================================

def construire_liste_ppn_complete(df_wikidata):

    # 1. Récupération des PPN GEN_AUT
    df_ppn = recuperer_ppn_gen_aut()

    # 2. Enrichissement Wikidata
    df_gen_aut = completer_avec_wikidata(df_ppn)

    # 3. Ajout de la raison
    df_gen_aut = df_gen_aut.copy()
    df_gen_aut["Raisons"] = "GEN_AUT"

    # 4. Fusion avec les PPN trouvés par Wikidata
    df_global = pd.concat(
        [df_wikidata, df_gen_aut],
        ignore_index=True
    )

    # 5. Nettoyage PPN
    df_global["ppn"] = (
        df_global["ppn"]
        .astype(str)
        .str.strip()
    )

    # 6. Suppression doublons
    df_global = (
        df_global
        .drop_duplicates(subset=["ppn"])
        .reset_index(drop=True)
    )

    # 7. Retrait Rousseau / Calvin
    ppn_a_retirer = {
        "028202368",
        "026763362"
    }

    df_global = (
        df_global[
            ~df_global["ppn"].isin(ppn_a_retirer)
        ]
        .reset_index(drop=True)
    )

    print(
        f"Liste finale : {len(df_global):,} PPN uniques"
    )

    return df_global