# -*- coding: utf-8 -*-
"""Copie de Sudoc.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17ex6ok1icY2JwKVHJOsNjZHitG-IXLtz
"""

import requests
import pandas as pd
import xml.etree.ElementTree as ET
import re
import time
import threading

from concurrent.futures import (
    ThreadPoolExecutor,
    as_completed
)

from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry


# ============================================================
# CONFIGURATION GÉNÉRALE
# ============================================================

SPARQL_URL = "https://data.idref.fr/sparql"

SUDOC_SRU_URL = (
    "https://www.sudoc.abes.fr/cbs/sru/"
)


CONNECT_TIMEOUT = 10
READ_TIMEOUT = 90

MAX_RETRIES = 3


# ============================================================
# CONFIGURATION OPTIMALE MESURÉE
# ============================================================

SPARQL_BATCH_SIZE = 50
SPARQL_WORKERS = 8

UNIMARC_BATCH_SIZE = 20
UNIMARC_WORKERS = 20

PICA_BATCH_SIZE = 20
PICA_WORKERS = 10


# ============================================================
# SESSION HTTP PAR THREAD
# ============================================================

thread_local = threading.local()


def creer_session(
    pool_size
):

    session = requests.Session()

    retry = Retry(

        total=MAX_RETRIES,

        connect=MAX_RETRIES,

        read=MAX_RETRIES,

        status=MAX_RETRIES,

        backoff_factor=0.5,

        status_forcelist=[
            429,
            500,
            502,
            503,
            504
        ],

        allowed_methods=[
            "GET",
            "POST"
        ],

        raise_on_status=False
    )

    adapter = HTTPAdapter(

        max_retries=retry,

        pool_connections=
            pool_size + 4,

        pool_maxsize=
            pool_size + 4
    )

    session.mount(
        "https://",
        adapter
    )

    session.headers.update({

        "User-Agent":
            "BGE-SUDOC-Optimisation-Finale/1.0",

        "Accept-Encoding":
            "gzip, deflate"
    })

    return session


def obtenir_session(
    pool_size
):

    cle = (
        f"session_{pool_size}"
    )

    if not hasattr(
        thread_local,
        cle
    ):

        setattr(
            thread_local,
            cle,
            creer_session(
                pool_size
            )
        )

    return getattr(
        thread_local,
        cle
    )


# ============================================================
# NORMALISATION PPN
# ============================================================

PPN_RE = re.compile(
    r"[^0-9X]"
)


def normaliser_ppn(
    valeur
):

    if pd.isna(
        valeur
    ):
        return None

    ppn = (
        str(valeur)
        .strip()
        .upper()
    )

    if ppn.endswith(
        ".0"
    ):

        ppn = ppn[:-2]

    ppn = PPN_RE.sub(
        "",
        ppn
    )

    if not ppn:
        return None

    if (
        ppn.isdigit()
        and len(ppn) < 9
    ):

        ppn = ppn.zfill(
            9
        )

    if not re.fullmatch(
        r"[0-9]{8}[0-9X]",
        ppn
    ):

        return None

    return ppn


# ============================================================
# ISBN
# ============================================================

ISBN10_RE = re.compile(
    r"\d{9}[\dX]"
)

ISBN13_RE = re.compile(
    r"\d{13}"
)

ISBN_DEBUT_RE = re.compile(
    r"^\s*([0-9X][0-9X\-\s]{8,30})"
)

ISBN_NETTOYAGE_RE = re.compile(
    r"[^0-9X]"
)


def isbn10_valide(
    isbn
):

    if not ISBN10_RE.fullmatch(
        isbn
    ):
        return False

    total = 0

    for i, c in enumerate(
        isbn
    ):

        valeur = (
            10
            if c == "X"
            else int(c)
        )

        total += (
            (10 - i)
            * valeur
        )

    return (
        total % 11
        == 0
    )


def isbn13_valide(
    isbn
):

    if not ISBN13_RE.fullmatch(
        isbn
    ):
        return False

    somme = 0

    for i, c in enumerate(
        isbn[:12]
    ):

        n = int(c)

        somme += (
            n
            if i % 2 == 0
            else n * 3
        )

    cle = (
        10
        - somme % 10
    ) % 10

    return (
        cle
        == int(
            isbn[-1]
        )
    )


def isbn10_vers_13(
    isbn10
):

    base = (
        "978"
        + isbn10[:9]
    )

    somme = 0

    for i, c in enumerate(
        base
    ):

        n = int(c)

        somme += (
            n
            if i % 2 == 0
            else n * 3
        )

    cle = (
        10
        - somme % 10
    ) % 10

    return (
        base
        + str(cle)
    )


def normaliser_isbn(
    valeur
):

    if not valeur:
        return None

    texte = (
        str(valeur)
        .upper()
        .strip()
    )

    match = (
        ISBN_DEBUT_RE
        .match(
            texte
        )
    )

    if match:

        texte = (
            match.group(1)
        )

    isbn = (
        ISBN_NETTOYAGE_RE
        .sub(
            "",
            texte
        )
    )

    if len(isbn) == 13:

        if isbn13_valide(
            isbn
        ):

            return isbn

        return None

    if len(isbn) == 10:

        if not isbn10_valide(
            isbn
        ):

            return None

        isbn13 = (
            isbn10_vers_13(
                isbn
            )
        )

        if isbn13_valide(
            isbn13
        ):

            return isbn13

    return None


# ============================================================
# OUTILS XML
# ============================================================

def nom_local(
    tag
):

    return tag.rsplit(
        "}",
        1
    )[-1]


def datafields(
    record,
    tag
):

    return [

        element

        for element
        in record.iter()

        if (
            nom_local(
                element.tag
            )
            == "datafield"

            and element.attrib.get(
                "tag"
            )
            == tag
        )
    ]


def controlfield(
    record,
    tag
):

    for element in record.iter():

        if (
            nom_local(
                element.tag
            )
            == "controlfield"

            and element.attrib.get(
                "tag"
            )
            == tag

            and element.text
        ):

            return (
                element.text
                .strip()
            )

    return None


def sous_champs(
    champ,
    code
):

    if champ is None:
        return []

    resultats = []

    for element in champ:

        if (
            nom_local(
                element.tag
            )
            == "subfield"

            and element.attrib.get(
                "code"
            )
            == code

            and element.text
        ):

            valeur = (
                element.text
                .strip()
            )

            if valeur:

                resultats.append(
                    valeur
                )

    return resultats


def sous_champ(
    champ,
    code
):

    valeurs = sous_champs(
        champ,
        code
    )

    return (
        valeurs[0]
        if valeurs
        else None
    )


def extraire_records(
    xml_bytes
):

    root = ET.fromstring(
        xml_bytes
    )

    records = []

    for element in root.iter():

        if (
            nom_local(
                element.tag
            )
            != "recordData"
        ):

            continue

        for enfant in element:

            if (
                nom_local(
                    enfant.tag
                )
                == "record"
            ):

                records.append(
                    enfant
                )

                break

    return records


# ============================================================
# ÉTAPE 1
#
# IDREF -> PPN SUDOC
# ============================================================

PPN_SUDOC_URI_RE = re.compile(
    r"sudoc\.fr/([0-9]{8}[0-9X])",
    re.I
)


def requete_sparql_lot(
    liste_ppn
):

    values = "\n".join(

        f'("{ppn}" '
        f'<http://www.idref.fr/{ppn}/id>)'

        for ppn
        in liste_ppn
    )

    query = f"""
SELECT DISTINCT
    ?ppn
    ?document

WHERE {{

    VALUES (?ppn ?idref) {{

        {values}

    }}

    ?document
        ?role
        ?idref .

    FILTER(

        STRSTARTS(
            STR(?document),
            "http://www.sudoc.fr/"
        )

    )

}}
"""

    session = obtenir_session(
        SPARQL_WORKERS
    )

    response = session.post(

        SPARQL_URL,

        data={
            "query":
                query,

            "format":
                "json"
        },

        headers={
            "Accept":
                "application/sparql-results+json"
        },

        timeout=(
            CONNECT_TIMEOUT,
            READ_TIMEOUT
        )
    )

    response.raise_for_status()

    bindings = (
        response
        .json()
        ["results"]
        ["bindings"]
    )

    mapping = []

    for ligne in bindings:

        try:

            ppn_idref = (
                ligne[
                    "ppn"
                ][
                    "value"
                ]
            )

            uri = (
                ligne[
                    "document"
                ][
                    "value"
                ]
            )

        except KeyError:

            continue

        match = (
            PPN_SUDOC_URI_RE
            .search(
                uri
            )
        )

        if not match:
            continue

        mapping.append(
            (
                ppn_idref,
                match
                .group(1)
                .upper()
            )
        )

    return mapping


def requete_sparql_robuste(
    liste_ppn
):

    try:

        return (
            requete_sparql_lot(
                liste_ppn
            )
        )

    except Exception:

        if len(
            liste_ppn
        ) <= 1:

            raise

        milieu = (
            len(
                liste_ppn
            )
            // 2
        )

        return (

            requete_sparql_robuste(
                liste_ppn[
                    :milieu
                ]
            )

            +

            requete_sparql_robuste(
                liste_ppn[
                    milieu:
                ]
            )
        )


def mapping_sparql_parallele(
    liste_ppn
):

    lots = [

        liste_ppn[
            i:
            i + SPARQL_BATCH_SIZE
        ]

        for i in range(
            0,
            len(
                liste_ppn
            ),
            SPARQL_BATCH_SIZE
        )
    ]

    mapping = []

    erreurs = []

    debut = (
        time.perf_counter()
    )

    print()
    print("=" * 100)
    print("1/4 — SPARQL IDREF -> SUDOC")
    print("=" * 100)

    print(
        f"PPN IdRef         : "
        f"{len(liste_ppn):,}"
    )

    print(
        f"Batch             : "
        f"{SPARQL_BATCH_SIZE}"
    )

    print(
        f"Workers           : "
        f"{SPARQL_WORKERS}"
    )

    print(
        f"Lots              : "
        f"{len(lots):,}"
    )

    with ThreadPoolExecutor(
        max_workers=
            SPARQL_WORKERS
    ) as executor:

        futures = {

            executor.submit(
                requete_sparql_robuste,
                lot
            ):
            lot

            for lot in lots
        }

        termines = 0

        for future in as_completed(
            futures
        ):

            termines += 1

            try:

                mapping.extend(
                    future.result()
                )

            except Exception:

                erreurs.extend(
                    futures[
                        future
                    ]
                )

            if (
                termines % 20 == 0
                or termines == len(
                    lots
                )
            ):

                print(
                    f"{termines:>4}/"
                    f"{len(lots)} lots "
                    f"| liens={len(mapping):,} "
                    f"| erreurs={len(erreurs):,}",
                    end="\r"
                )

    duree = (
        time.perf_counter()
        - debut
    )

    mapping = list(
        dict.fromkeys(
            mapping
        )
    )

    print()
    print()

    print(
        f"Durée SPARQL      : "
        f"{duree:.3f} s"
    )

    print(
        f"Liens uniques     : "
        f"{len(mapping):,}"
    )

    print(
        f"Erreurs           : "
        f"{len(erreurs):,}"
    )

    return (
        mapping,
        erreurs,
        duree
    )


# ============================================================
# REQUÊTE SRU GÉNÉRIQUE
# ============================================================

def requete_sru_lot(
    lot,
    schema,
    workers
):

    if schema == "pica":

        query = " or ".join(

            f"pica.ppn={ppn}"

            for ppn
            in lot
        )

    else:

        query = " or ".join(

            f"ppn={ppn}"

            for ppn
            in lot
        )

    session = obtenir_session(
        workers
    )

    response = session.get(

        SUDOC_SRU_URL,

        params={
            "version":
                "1.1",

            "operation":
                "searchRetrieve",

            "recordSchema":
                schema,

            "query":
                query,

            "startRecord":
                1,

            "maximumRecords":
                len(
                    lot
                )
        },

        timeout=(
            CONNECT_TIMEOUT,
            READ_TIMEOUT
        )
    )

    response.raise_for_status()

    return (
        response.content
    )


# ============================================================
# FALLBACK SRU
# ============================================================

def requete_sru_robuste(
    lot,
    schema,
    workers
):

    try:

        return [
            requete_sru_lot(
                lot,
                schema,
                workers
            )
        ]

    except Exception:

        if len(
            lot
        ) <= 1:

            raise

        milieu = (
            len(
                lot
            )
            // 2
        )

        return (

            requete_sru_robuste(
                lot[:milieu],
                schema,
                workers
            )

            +

            requete_sru_robuste(
                lot[milieu:],
                schema,
                workers
            )
        )


# ============================================================
# PARSER UNIMARC COMPLET
# ============================================================

def nettoyer_texte(
    texte
):

    if not texte:
        return None

    texte = (
        str(texte)
        .strip()
    )

    texte = re.sub(
        r"\s*[/:;,]\s*$",
        "",
        texte
    )

    return (
        texte
        or None
    )


ANNEE_RE = re.compile(
    r"\b(1[0-9]{3}|20[0-9]{2}|21[0-9]{2})\b"
)


def extraire_annee(
    valeurs
):

    for valeur in valeurs:

        if not valeur:
            continue

        match = (
            ANNEE_RE.search(
                str(
                    valeur
                )
            )
        )

        if match:

            return int(
                match.group(1)
            )

    return None


def parser_unimarc(
    record
):

    ppn = normaliser_ppn(

        controlfield(
            record,
            "001"
        )
    )

    if not ppn:
        return None

    # ========================================================
    # ISBN
    # ========================================================

    isbns = []

    for champ in datafields(
        record,
        "010"
    ):

        for valeur in sous_champs(
            champ,
            "a"
        ):

            isbn = normaliser_isbn(
                valeur
            )

            if isbn:

                isbns.append(
                    isbn
                )

    isbns = list(
        dict.fromkeys(
            isbns
        )
    )

    # Pas d'ISBN :
    # on ne parse pas le reste.
    if not isbns:

        return {
            "ppn":
                ppn,

            "isbns":
                []
        }

    # ========================================================
    # TITRE
    # ========================================================

    champs200 = datafields(
        record,
        "200"
    )

    champ200 = (
        champs200[0]
        if champs200
        else None
    )

    titres = [

        texte

        for valeur
        in sous_champs(
            champ200,
            "a"
        )

        if (
            texte :=
            nettoyer_texte(
                valeur
            )
        )
    ]

    sous_titres = [

        texte

        for valeur
        in sous_champs(
            champ200,
            "e"
        )

        if (
            texte :=
            nettoyer_texte(
                valeur
            )
        )
    ]

    titres = list(
        dict.fromkeys(
            titres
        )
    )

    sous_titres = list(
        dict.fromkeys(
            sous_titres
        )
    )

    titre = (
        " ; ".join(
            titres
        )
        if titres
        else None
    )

    sous_titre = (
        " ; ".join(
            sous_titres
        )
        if sous_titres
        else None
    )

    if (
        titre
        and sous_titre
    ):

        titre = (
            f"{titre} : "
            f"{sous_titre}"
        )

    elif not titre:

        titre = (
            sous_titre
        )

    # ========================================================
    # AUTEUR
    # ========================================================

    auteur = None

    champs_auteur = (
        datafields(
            record,
            "700"
        )
    )

    if not champs_auteur:

        champs_auteur = (
            datafields(
                record,
                "701"
            )
        )

    if champs_auteur:

        champ = (
            champs_auteur[0]
        )

        nom = nettoyer_texte(

            sous_champ(
                champ,
                "a"
            )
        )

        prenom = nettoyer_texte(

            sous_champ(
                champ,
                "b"
            )
        )

        if (
            nom
            and prenom
        ):

            auteur = (
                f"{nom}, {prenom}"
            )

        else:

            auteur = (
                nom
                or prenom
            )

    # ========================================================
    # PUBLICATION
    # ========================================================

    publication = (
        datafields(
            record,
            "214"
        )
    )

    if not publication:

        publication = (
            datafields(
                record,
                "210"
            )
        )

    lieux = []
    editeurs = []
    annees = []

    for champ in publication:

        lieux.extend(
            sous_champs(
                champ,
                "a"
            )
        )

        editeurs.extend(
            sous_champs(
                champ,
                "c"
            )
        )

        annees.extend(
            sous_champs(
                champ,
                "d"
            )
        )

    lieux = [

        texte

        for valeur
        in lieux

        if (
            texte :=
            nettoyer_texte(
                valeur
            )
        )
    ]

    editeurs = [

        texte

        for valeur
        in editeurs

        if (
            texte :=
            nettoyer_texte(
                valeur
            )
        )
    ]

    lieux = list(
        dict.fromkeys(
            lieux
        )
    )

    editeurs = list(
        dict.fromkeys(
            editeurs
        )
    )

    lieu = (
        " - ".join(
            lieux
        )
        if lieux
        else None
    )

    editeur = (
        " - ".join(
            editeurs
        )
        if editeurs
        else None
    )

    annee = (
        extraire_annee(
            annees
        )
    )

    return {

        "ppn":
            ppn,

        "isbns":
            isbns,

        "titre":
            titre,

        "annee":
            annee,

        "nomAuteur":
            auteur,

        "lieuPublication":
            lieu,

        "editeur":
            editeur
    }


# ============================================================
# TRAITEMENT LOT UNIMARC
# ============================================================

def traiter_lot_unimarc(
    lot
):

    resultats = {}

    erreurs = []

    try:

        reponses = (
            requete_sru_robuste(
                lot,
                "unimarc",
                UNIMARC_WORKERS
            )
        )

        for xml_bytes in reponses:

            records = (
                extraire_records(
                    xml_bytes
                )
            )

            for record in records:

                notice = (
                    parser_unimarc(
                        record
                    )
                )

                if not notice:
                    continue

                resultats[
                    notice[
                        "ppn"
                    ]
                ] = notice

    except Exception:

        erreurs.extend(
            lot
        )

    return (
        resultats,
        erreurs
    )


# ============================================================
# ÉTAPE 2
#
# UNIMARC COMPLET
# ============================================================

def recuperer_unimarc_complet(
    liste_ppn
):

    lots = [

        liste_ppn[
            i:
            i + UNIMARC_BATCH_SIZE
        ]

        for i in range(
            0,
            len(
                liste_ppn
            ),
            UNIMARC_BATCH_SIZE
        )
    ]

    notices = {}

    erreurs = []

    debut = (
        time.perf_counter()
    )

    print()
    print("=" * 100)
    print("2/4 — UNIMARC")
    print("=" * 100)

    print(
        f"PPN SUDOC        : "
        f"{len(liste_ppn):,}"
    )

    print(
        f"Batch            : "
        f"{UNIMARC_BATCH_SIZE}"
    )

    print(
        f"Workers          : "
        f"{UNIMARC_WORKERS}"
    )

    print(
        f"Lots             : "
        f"{len(lots):,}"
    )

    with ThreadPoolExecutor(
        max_workers=
            UNIMARC_WORKERS
    ) as executor:

        futures = {

            executor.submit(
                traiter_lot_unimarc,
                lot
            ):
            lot

            for lot in lots
        }

        termines = 0

        for future in as_completed(
            futures
        ):

            termines += 1

            try:

                notices_lot, erreurs_lot = (
                    future.result()
                )

                notices.update(
                    notices_lot
                )

                erreurs.extend(
                    erreurs_lot
                )

            except Exception:

                erreurs.extend(
                    futures[
                        future
                    ]
                )

            if (
                termines % 100 == 0
                or termines == len(
                    lots
                )
            ):

                ecoule = (
                    time.perf_counter()
                    - debut
                )

                print(
                    f"{termines:>5}/"
                    f"{len(lots)} lots "
                    f"| notices={len(notices):,} "
                    f"| erreurs={len(erreurs):,} "
                    f"| {ecoule:.1f}s",
                    end="\r"
                )

    duree = (
        time.perf_counter()
        - debut
    )

    print()
    print()

    print(
        f"Durée UNIMARC    : "
        f"{duree:.3f} s"
    )

    print(
        f"Notices reçues   : "
        f"{len(notices):,}"
    )

    print(
        f"Erreurs          : "
        f"{len(erreurs):,}"
    )

    return (
        notices,
        erreurs,
        duree
    )


# ============================================================
# PPN AVEC ISBN
# ============================================================

def extraire_ppn_avec_isbn(
    notices
):

    return [

        ppn

        for ppn, notice
        in notices.items()

        if notice.get(
            "isbns"
        )
    ]


# ============================================================
# PARSER PICA CEB
# ============================================================

def parser_pica_ceb(
    record
):

    champs_ppn = (
        datafields(
            record,
            "003@"
        )
    )

    if not champs_ppn:
        return None

    ppn = normaliser_ppn(

        sous_champ(
            champs_ppn[0],
            "0"
        )
    )

    if not ppn:
        return None

    ceb = False

    for champ in datafields(
        record,
        "012V"
    ):

        for valeur in sous_champs(
            champ,
            "c"
        ):

            if (
                valeur
                .strip()
                .lower()
                == "ceb"
            ):

                ceb = True
                break

        if ceb:
            break

    return (
        ppn,
        ceb
    )


# ============================================================
# TRAITEMENT LOT PICA
# ============================================================

def traiter_lot_pica(
    lot
):

    analyses = {}

    erreurs = []

    try:

        reponses = (
            requete_sru_robuste(
                lot,
                "pica",
                PICA_WORKERS
            )
        )

        for xml_bytes in reponses:

            records = (
                extraire_records(
                    xml_bytes
                )
            )

            for record in records:

                resultat = (
                    parser_pica_ceb(
                        record
                    )
                )

                if not resultat:
                    continue

                ppn, ceb = (
                    resultat
                )

                analyses[
                    ppn
                ] = ceb

    except Exception:

        erreurs.extend(
            lot
        )

    return (
        analyses,
        erreurs
    )


# ============================================================
# ÉTAPE 3
#
# PICA CIBLÉ
# ============================================================

def recuperer_ceb_cible(
    liste_ppn
):

    lots = [

        liste_ppn[
            i:
            i + PICA_BATCH_SIZE
        ]

        for i in range(
            0,
            len(
                liste_ppn
            ),
            PICA_BATCH_SIZE
        )
    ]

    analyses = {}

    erreurs = []

    debut = (
        time.perf_counter()
    )

    print()
    print("=" * 100)
    print("3/4 — PICA CIBLÉ 012V$c = ceb")
    print("=" * 100)

    print(
        f"PPN avec ISBN    : "
        f"{len(liste_ppn):,}"
    )

    print(
        f"Batch            : "
        f"{PICA_BATCH_SIZE}"
    )

    print(
        f"Workers          : "
        f"{PICA_WORKERS}"
    )

    print(
        f"Lots             : "
        f"{len(lots):,}"
    )

    with ThreadPoolExecutor(
        max_workers=
            PICA_WORKERS
    ) as executor:

        futures = {

            executor.submit(
                traiter_lot_pica,
                lot
            ):
            lot

            for lot in lots
        }

        termines = 0

        for future in as_completed(
            futures
        ):

            termines += 1

            try:

                analyses_lot, erreurs_lot = (
                    future.result()
                )

                analyses.update(
                    analyses_lot
                )

                erreurs.extend(
                    erreurs_lot
                )

            except Exception:

                erreurs.extend(
                    futures[
                        future
                    ]
                )

            if (
                termines % 25 == 0
                or termines == len(
                    lots
                )
            ):

                print(
                    f"{termines:>4}/"
                    f"{len(lots)} lots "
                    f"| analysés={len(analyses):,} "
                    f"| erreurs={len(erreurs):,}",
                    end="\r"
                )

    duree = (
        time.perf_counter()
        - debut
    )

    demandes = set(
        liste_ppn
    )

    recus = set(
        analyses
    )

    manquants = (
        demandes
        - recus
    )

    ppn_ceb = {

        ppn

        for ppn, ceb
        in analyses.items()

        if ceb
    }

    print()
    print()

    print(
        f"Durée PICA       : "
        f"{duree:.3f} s"
    )

    print(
        f"PPN analysés     : "
        f"{len(analyses):,}"
    )

    print(
        f"CEB              : "
        f"{len(ppn_ceb):,}"
    )

    print(
        f"PPN PICA absents : "
        f"{len(manquants):,}"
    )

    print(
        f"Erreurs          : "
        f"{len(erreurs):,}"
    )

    return (
        ppn_ceb,
        manquants,
        erreurs,
        duree
    )


# ============================================================
# ÉTAPE 4
#
# CONSTRUCTION DU RÉSULTAT FINAL
# ============================================================

def construire_resultat_final(
    mapping,
    notices,
    ppn_ceb
):

    debut = (
        time.perf_counter()
    )

    lignes = []

    append = (
        lignes.append
    )

    for (
        ppn_idref,
        ppn_sudoc
    ) in mapping:

        # ----------------------------------------------------
        # EXCLUSION CEB
        # ----------------------------------------------------

        if ppn_sudoc in ppn_ceb:
            continue

        notice = notices.get(
            ppn_sudoc
        )

        if not notice:
            continue

        isbns = notice.get(
            "isbns"
        )

        if not isbns:
            continue

        for isbn in isbns:

            append({

                "ppn":
                    ppn_idref,

                "ppn_sudoc":
                    ppn_sudoc,

                "isbn":
                    isbn,

                "titre":
                    notice.get(
                        "titre"
                    ),

                "annee":
                    notice.get(
                        "annee"
                    ),

                "nomAuteur":
                    notice.get(
                        "nomAuteur"
                    ),

                "lieuPublication":
                    notice.get(
                        "lieuPublication"
                    ),

                "editeur":
                    notice.get(
                        "editeur"
                    )
            })

    df = pd.DataFrame.from_records(
        lignes
    )

    if not df.empty:

        df.drop_duplicates(

            subset=[
                "ppn",
                "isbn"
            ],

            keep="first",

            inplace=True
        )

        df[
            "ppn"
        ] = (
            df[
                "ppn"
            ]
            .astype(
                "string"
            )
        )

        df[
            "ppn_sudoc"
        ] = (
            df[
                "ppn_sudoc"
            ]
            .astype(
                "string"
            )
        )

        df[
            "isbn"
        ] = (
            df[
                "isbn"
            ]
            .astype(
                "string"
            )
        )

        df[
            "annee"
        ] = (
            pd.to_numeric(
                df[
                    "annee"
                ],
                errors="coerce"
            )
            .astype(
                "Int64"
            )
        )

        df.reset_index(
            drop=True,
            inplace=True
        )

    duree = (
        time.perf_counter()
        - debut
    )

    return (
        df,
        duree
    )


# ============================================================
# PIPELINE FINAL DE BENCHMARK
# ============================================================

def benchmark_pipeline_sudoc_final(
    liste_ppn_idref
):

    debut_total = (
        time.perf_counter()
    )

    # ========================================================
    # PRÉPARATION
    # ========================================================

    liste_ppn_idref = [

        ppn

        for valeur
        in liste_ppn_idref

        if (
            ppn :=
            normaliser_ppn(
                valeur
            )
        )
    ]

    liste_ppn_idref = list(
        dict.fromkeys(
            liste_ppn_idref
        )
    )

    print()
    print("#" * 100)
    print("BENCHMARK FINAL PIPELINE SUDOC")
    print("#" * 100)

    print(
        f"PPN IdRef uniques : "
        f"{len(liste_ppn_idref):,}"
    )

    # ========================================================
    # 1. SPARQL
    # ========================================================

    (
        mapping,
        erreurs_sparql,
        duree_sparql
    ) = (
        mapping_sparql_parallele(
            liste_ppn_idref
        )
    )

    # ========================================================
    # PPN SUDOC UNIQUES
    # ========================================================

    liste_ppn_sudoc = list(
        dict.fromkeys(

            ppn_sudoc

            for (
                _,
                ppn_sudoc
            )
            in mapping
        )
    )

    print()
    print(
        f"PPN SUDOC uniques : "
        f"{len(liste_ppn_sudoc):,}"
    )

    # ========================================================
    # 2. UNIMARC
    # ========================================================

    (
        notices,
        erreurs_unimarc,
        duree_unimarc
    ) = (
        recuperer_unimarc_complet(
            liste_ppn_sudoc
        )
    )

    # ========================================================
    # ISBN
    # ========================================================

    ppn_avec_isbn = (
        extraire_ppn_avec_isbn(
            notices
        )
    )

    print()
    print(
        f"PPN avec ISBN     : "
        f"{len(ppn_avec_isbn):,}"
    )

    # ========================================================
    # 3. PICA CIBLÉ
    # ========================================================

    (
        ppn_ceb,
        ppn_pica_absents,
        erreurs_pica,
        duree_pica
    ) = (
        recuperer_ceb_cible(
            ppn_avec_isbn
        )
    )

    # ========================================================
    # 4. DATAFRAME
    # ========================================================

    print()
    print("=" * 100)
    print("4/4 — CONSTRUCTION DATAFRAME")
    print("=" * 100)

    (
        resultat,
        duree_dataframe
    ) = (
        construire_resultat_final(
            mapping,
            notices,
            ppn_ceb
        )
    )

    duree_totale = (
        time.perf_counter()
        - debut_total
    )

    # ========================================================
    # CONTRÔLES
    # ========================================================

    ppn_isbn_apres_ceb = (
        set(
            ppn_avec_isbn
        )
        - ppn_ceb
    )

    # ========================================================
    # BILAN
    # ========================================================

    print()
    print()
    print("#" * 100)
    print("RÉSULTAT FINAL DU BENCHMARK")
    print("#" * 100)

    print()
    print("VOLUMES")
    print("-" * 100)

    print(
        f"PPN IdRef                    : "
        f"{len(liste_ppn_idref):,}"
    )

    print(
        f"Liens IdRef -> SUDOC         : "
        f"{len(mapping):,}"
    )

    print(
        f"PPN SUDOC uniques            : "
        f"{len(liste_ppn_sudoc):,}"
    )

    print(
        f"Notices UNIMARC reçues       : "
        f"{len(notices):,}"
    )

    print(
        f"PPN avec ISBN avant CEB      : "
        f"{len(ppn_avec_isbn):,}"
    )

    print(
        f"PPN CEB                      : "
        f"{len(ppn_ceb):,}"
    )

    print(
        f"PPN avec ISBN après CEB      : "
        f"{len(ppn_isbn_apres_ceb):,}"
    )

    print(
        f"PPN PICA absents             : "
        f"{len(ppn_pica_absents):,}"
    )

    print(
        f"Lignes DataFrame final       : "
        f"{len(resultat):,}"
    )

    if not resultat.empty:

        print(
            f"ISBN uniques                 : "
            f"{resultat['isbn'].nunique():,}"
        )

        print(
            f"PPN IdRef présents           : "
            f"{resultat['ppn'].nunique():,}"
        )

        print(
            f"PPN SUDOC présents           : "
            f"{resultat['ppn_sudoc'].nunique():,}"
        )

    print()
    print("TEMPS")
    print("-" * 100)

    print(
        f"SPARQL                       : "
        f"{duree_sparql:.3f} s"
    )

    print(
        f"UNIMARC                      : "
        f"{duree_unimarc:.3f} s"
    )

    print(
        f"PICA ciblé                   : "
        f"{duree_pica:.3f} s"
    )

    print(
        f"Construction DataFrame       : "
        f"{duree_dataframe:.3f} s"
    )

    print()

    print(
        f"DURÉE TOTALE                 : "
        f"{duree_totale:.3f} s"
    )

    print(
        f"DURÉE TOTALE                 : "
        f"{duree_totale / 60:.2f} min"
    )

    print()
    print("ERREURS")
    print("-" * 100)

    print(
        f"Erreurs SPARQL               : "
        f"{len(erreurs_sparql):,}"
    )

    print(
        f"Erreurs UNIMARC              : "
        f"{len(erreurs_unimarc):,}"
    )

    print(
        f"Erreurs PICA                 : "
        f"{len(erreurs_pica):,}"
    )

    print()
    print("CONFIGURATION")
    print("-" * 100)

    print(
        f"SPARQL : "
        f"batch={SPARQL_BATCH_SIZE} "
        f"/ workers={SPARQL_WORKERS}"
    )

    print(
        f"UNIMARC: "
        f"batch={UNIMARC_BATCH_SIZE} "
        f"/ workers={UNIMARC_WORKERS}"
    )

    print(
        f"PICA   : "
        f"batch={PICA_BATCH_SIZE} "
        f"/ workers={PICA_WORKERS}"
    )

    print("#" * 100)

    # ========================================================
    # ATTRS
    # ========================================================

    resultat.attrs[
        "erreurs_sparql"
    ] = erreurs_sparql

    resultat.attrs[
        "erreurs_unimarc"
    ] = erreurs_unimarc

    resultat.attrs[
        "erreurs_pica"
    ] = erreurs_pica

    resultat.attrs[
        "ppn_ceb"
    ] = sorted(
        ppn_ceb
    )

    resultat.attrs[
        "ppn_pica_absents"
    ] = sorted(
        ppn_pica_absents
    )

    resultat.attrs[
        "duree_sparql"
    ] = duree_sparql

    resultat.attrs[
        "duree_unimarc"
    ] = duree_unimarc

    resultat.attrs[
        "duree_pica"
    ] = duree_pica

    resultat.attrs[
        "duree_totale"
    ] = duree_totale

    return resultat


# ============================================================
# FONCTION DE PRODUCTION — COMPATIBILITÉ SOURCES.PY
# ============================================================

def ajouter_isbn_sudoc_ultra(
    df,
    colonne_ppn="ppn"
):
    """
    Fonction publique appelée par sources.py.

    Paramètres
    ----------
    df : pandas.DataFrame
        DataFrame contenant les PPN IdRef auteurs.

    colonne_ppn : str
        Nom de la colonne contenant les PPN IdRef.

    Retour
    ------
    pandas.DataFrame
        DataFrame compatible avec fusion.py, contenant notamment :
        - ppn
        - isbn_normalise
        - titre
        - annee
        - nomAuteur
        - lieuPublication
        - editeur
        - ppn_sudoc

        Les colonnes originales du DataFrame d'entrée sont conservées.
    """

    # ========================================================
    # CONTRÔLES
    # ========================================================

    if df is None:

        raise ValueError(
            "Le DataFrame fourni à ajouter_isbn_sudoc_ultra est None."
        )

    if not isinstance(
        df,
        pd.DataFrame
    ):

        raise TypeError(
            f"Objet reçu invalide : {type(df)}"
        )

    if colonne_ppn not in df.columns:

        raise ValueError(
            f"La colonne '{colonne_ppn}' n'existe pas."
        )

    # ========================================================
    # COPIE SOURCE
    # ========================================================

    source = df.copy()

    # --------------------------------------------------------
    # Supprimer d'anciennes colonnes SUDOC éventuelles
    # pour éviter les suffixes _x / _y au merge.
    # --------------------------------------------------------

    colonnes_sudoc = [
        "ppn_sudoc",
        "isbn",
        "isbn_normalise",
        "titre",
        "annee",
        "nomAuteur",
        "lieuPublication",
        "editeur"
    ]

    colonnes_a_supprimer = [
        col
        for col in colonnes_sudoc
        if col in source.columns
    ]

    if colonnes_a_supprimer:

        source.drop(
            columns=colonnes_a_supprimer,
            inplace=True
        )

    colonnes_originales = list(
        source.columns
    )

    # ========================================================
    # PPN TECHNIQUE NORMALISÉ
    # ========================================================

    source["_ppn_requete"] = (
        source[
            colonne_ppn
        ]
        .map(
            normaliser_ppn
        )
    )

    liste_ppn_idref = (
        source[
            "_ppn_requete"
        ]
        .dropna()
        .drop_duplicates()
        .tolist()
    )

    print()
    print("#" * 100)
    print("SUDOC — VERSION DE PRODUCTION OPTIMISÉE")
    print("#" * 100)

    print(
        f"PPN IdRef uniques : "
        f"{len(liste_ppn_idref):,}"
    )

    # ========================================================
    # AUCUN PPN
    # ========================================================

    if not liste_ppn_idref:

        resultat = pd.DataFrame(
            columns=(
                colonnes_originales
                + [
                    "ppn_sudoc",
                    "isbn_normalise",
                    "titre",
                    "annee",
                    "nomAuteur",
                    "lieuPublication",
                    "editeur"
                ]
            )
        )

        return resultat

    debut_total = (
        time.perf_counter()
    )

    # ========================================================
    # 1. SPARQL IDREF -> PPN SUDOC
    # ========================================================

    (
        mapping,
        erreurs_sparql,
        duree_sparql
    ) = (
        mapping_sparql_parallele(
            liste_ppn_idref
        )
    )

    if not mapping:

        resultat = pd.DataFrame(
            columns=(
                colonnes_originales
                + [
                    "ppn_sudoc",
                    "isbn_normalise",
                    "titre",
                    "annee",
                    "nomAuteur",
                    "lieuPublication",
                    "editeur"
                ]
            )
        )

        resultat.attrs[
            "erreurs_sparql"
        ] = erreurs_sparql

        resultat.attrs[
            "erreurs_unimarc"
        ] = []

        resultat.attrs[
            "erreurs_pica"
        ] = []

        return resultat

    # ========================================================
    # PPN SUDOC UNIQUES
    # ========================================================

    liste_ppn_sudoc = list(
        dict.fromkeys(
            ppn_sudoc
            for (
                _,
                ppn_sudoc
            )
            in mapping
        )
    )

    print()
    print(
        f"PPN SUDOC uniques : "
        f"{len(liste_ppn_sudoc):,}"
    )

    # ========================================================
    # 2. UNIMARC
    # ========================================================

    (
        notices,
        erreurs_unimarc,
        duree_unimarc
    ) = (
        recuperer_unimarc_complet(
            liste_ppn_sudoc
        )
    )

    # ========================================================
    # PPN AVEC ISBN
    # ========================================================

    ppn_avec_isbn = (
        extraire_ppn_avec_isbn(
            notices
        )
    )

    print()
    print(
        f"PPN avec ISBN     : "
        f"{len(ppn_avec_isbn):,}"
    )

    # ========================================================
    # 3. PICA CIBLÉ — CEB
    # ========================================================

    (
        ppn_ceb,
        ppn_pica_absents,
        erreurs_pica,
        duree_pica
    ) = (
        recuperer_ceb_cible(
            ppn_avec_isbn
        )
    )

    # ========================================================
    # 4. CONSTRUCTION DES LIGNES SUDOC
    # ========================================================

    lignes = []

    append = lignes.append

    for (
        ppn_idref,
        ppn_sudoc
    ) in mapping:

        # Notice CEB = exclusion totale
        if ppn_sudoc in ppn_ceb:
            continue

        notice = notices.get(
            ppn_sudoc
        )

        if not notice:
            continue

        isbns = notice.get(
            "isbns"
        )

        if not isbns:
            continue

        for isbn in isbns:

            append({

                "_ppn_requete":
                    ppn_idref,

                "ppn_sudoc":
                    ppn_sudoc,

                "isbn_normalise":
                    isbn,

                "titre":
                    notice.get(
                        "titre"
                    ),

                "annee":
                    notice.get(
                        "annee"
                    ),

                "nomAuteur":
                    notice.get(
                        "nomAuteur"
                    ),

                "lieuPublication":
                    notice.get(
                        "lieuPublication"
                    ),

                "editeur":
                    notice.get(
                        "editeur"
                    )
            })

    # ========================================================
    # AUCUNE LIGNE
    # ========================================================

    if not lignes:

        resultat = pd.DataFrame(
            columns=(
                colonnes_originales
                + [
                    "ppn_sudoc",
                    "isbn_normalise",
                    "titre",
                    "annee",
                    "nomAuteur",
                    "lieuPublication",
                    "editeur"
                ]
            )
        )

        resultat.attrs[
            "erreurs_sparql"
        ] = erreurs_sparql

        resultat.attrs[
            "erreurs_unimarc"
        ] = erreurs_unimarc

        resultat.attrs[
            "erreurs_pica"
        ] = erreurs_pica

        resultat.attrs[
            "ppn_ceb"
        ] = sorted(
            ppn_ceb
        )

        resultat.attrs[
            "ppn_pica_absents"
        ] = sorted(
            ppn_pica_absents
        )

        return resultat

    # ========================================================
    # DATAFRAME SUDOC
    # ========================================================

    df_sudoc = pd.DataFrame.from_records(
        lignes
    )

    # --------------------------------------------------------
    # Dédoublonnage technique :
    # même auteur IdRef + même ISBN
    # --------------------------------------------------------

    df_sudoc.drop_duplicates(
        subset=[
            "_ppn_requete",
            "isbn_normalise"
        ],
        keep="first",
        inplace=True
    )

    # ========================================================
    # MERGE AVEC LE DATAFRAME SOURCE
    # ========================================================

    resultat = source.merge(

        df_sudoc,

        on="_ppn_requete",

        how="inner",

        sort=False,

        copy=False
    )

    resultat.drop(
        columns=[
            "_ppn_requete"
        ],
        inplace=True
    )

    # ========================================================
    # TYPES
    # ========================================================

    if colonne_ppn in resultat.columns:

        resultat[
            colonne_ppn
        ] = (
            resultat[
                colonne_ppn
            ]
            .astype(
                "string"
            )
        )

    resultat[
        "ppn_sudoc"
    ] = (
        resultat[
            "ppn_sudoc"
        ]
        .astype(
            "string"
        )
    )

    resultat[
        "isbn_normalise"
    ] = (
        resultat[
            "isbn_normalise"
        ]
        .astype(
            "string"
        )
    )

    resultat[
        "annee"
    ] = (
        pd.to_numeric(
            resultat[
                "annee"
            ],
            errors="coerce"
        )
        .astype(
            "Int64"
        )
    )

    resultat.reset_index(
        drop=True,
        inplace=True
    )

    # ========================================================
    # ATTRIBUTS DE DIAGNOSTIC
    # ========================================================

    resultat.attrs[
        "erreurs_sparql"
    ] = erreurs_sparql

    resultat.attrs[
        "erreurs_unimarc"
    ] = erreurs_unimarc

    resultat.attrs[
        "erreurs_sru"
    ] = erreurs_unimarc

    resultat.attrs[
        "erreurs_pica"
    ] = erreurs_pica

    resultat.attrs[
        "ppn_ceb"
    ] = sorted(
        ppn_ceb
    )

    resultat.attrs[
        "ppn_pica_absents"
    ] = sorted(
        ppn_pica_absents
    )

    resultat.attrs[
        "duree_sparql"
    ] = duree_sparql

    resultat.attrs[
        "duree_unimarc"
    ] = duree_unimarc

    resultat.attrs[
        "duree_pica"
    ] = duree_pica

    duree_totale = (
        time.perf_counter()
        - debut_total
    )

    resultat.attrs[
        "duree_totale"
    ] = duree_totale

    # ========================================================
    # BILAN
    # ========================================================

    print()
    print("#" * 100)
    print("SUDOC TERMINÉ")
    print("#" * 100)

    print(
        f"Liens IdRef/SUDOC     : "
        f"{len(mapping):,}"
    )

    print(
        f"PPN SUDOC uniques     : "
        f"{len(liste_ppn_sudoc):,}"
    )

    print(
        f"PPN avec ISBN         : "
        f"{len(ppn_avec_isbn):,}"
    )

    print(
        f"PPN CEB exclus        : "
        f"{len(ppn_ceb):,}"
    )

    print(
        f"Lignes finales SUDOC  : "
        f"{len(resultat):,}"
    )

    print()

    print(
        f"SPARQL                : "
        f"{duree_sparql:.2f} s"
    )

    print(
        f"UNIMARC               : "
        f"{duree_unimarc:.2f} s"
    )

    print(
        f"PICA ciblé            : "
        f"{duree_pica:.2f} s"
    )

    print(
        f"TOTAL SUDOC           : "
        f"{duree_totale:.2f} s "
        f"({duree_totale / 60:.2f} min)"
    )

    print("#" * 100)

    return resultat